sudo: required
language: node_js
node_js:
  - 8.2.1
cache:
  directories:
    - node_modules # NPM packages
install:
  - npm install
script:
  - npx gitbook update
  - npm run build
branches:
  only:
    - master
deploy:
  provider: pages
  local_dir: _book
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
notifications:
  email: false